controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

cart_index:
  path: /cart
  controller: App\Controller\CartController::index

add_to_cart:
    path: /cart/add/{id}
    controller: App\Controller\CartController::add
    methods: POST